project:
  type: website
  output-dir: docs

website:
  site-url: https://jenswaaben.github.io/stats_notes/
  title: "Statistics Notes"
  navbar:
    left:
      - text: "Home"
        file: index.qmd
      - text: "Introduction"
        file: 01_introduction/index.qmd
      - text: "Distributions"
        file: 02_distributions/index.qmd
      - text: "Statistical Inference"
        file: 03_statistical_inference/index.qmd
      - text: "Machine Learning"
        file: 04_machine_learning/index.qmd

format:
  html:
    code-overflow: scroll
    theme: cosmo
    scss: styles.scss
    toc: true
    toc-location: left
    page-layout: full
    grid: 
      sidebar-width: 
        275px
      gutter-width: 
        1em
      margin-width: 
        400px
